// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/atla/AtlaAbout.tsx": () => import("../components/mockups/atla/AtlaAbout.tsx"),
  "./components/mockups/atla/AtlaHome.tsx": () => import("../components/mockups/atla/AtlaHome.tsx"),
  "./components/mockups/atla/AtlaProject.tsx": () => import("../components/mockups/atla/AtlaProject.tsx"),
  "./components/mockups/atla/AtlaWork.tsx": () => import("../components/mockups/atla/AtlaWork.tsx")
};
