export type SeedProject = {
  id: string;
  slug: string;
  title: string;
  client: string;
  year: number;
  category: string;
  tags: string[];
  description: string;
  body: string;
  coverImage: string;
  images: string[];
  featured: boolean;
  status: string;
  createdAt: Date;
};

const now = new Date("2026-03-12T12:00:00.000Z");

export const seedProjects: SeedProject[] = [
  {
    id: "reggie",
    slug: "reggie",
    title: "Reggie",
    client: "Meridian Architecture",
    year: 2025,
    category: "Brand Identity",
    tags: ["Branding", "UX/UI Design", "3D Experience"],
    description: "A reimagined identity for a boutique creative agency specializing in photography and editorial campaigns.",
    body: "Reggie is a science-backed brand identity system built to feel warm, credible, and contemporary across packaging and digital touchpoints.",
    coverImage: "https://www.figma.com/api/mcp/asset/8ab2b981-c253-48a1-a51d-a42dfdcc0043",
    images: [
      "https://www.figma.com/api/mcp/asset/bb93b353-41a0-4557-bc12-8e61a3bb916f",
      "https://www.figma.com/api/mcp/asset/49a43170-4ba3-414d-a1c5-37162e343eaf",
      "https://www.figma.com/api/mcp/asset/7c3e1a84-6cd6-4609-bdf6-607ddf53acf0",
    ],
    featured: true,
    status: "published",
    createdAt: now,
  },
  {
    id: "digital-poetics",
    slug: "digital-poetics",
    title: "Digital Poetics",
    client: "Sonori",
    year: 2025,
    category: "Digital Experience",
    tags: ["Website", "Motion", "Editorial"],
    description: "A cinematic digital system where editorial motion and tactile interactions become the brand language.",
    body: "Digital Poetics explores motion, interaction, and editorial rhythm as the core material of the brand.",
    coverImage: "https://www.figma.com/api/mcp/asset/c4064624-f944-4dc7-ba93-2fdcc3f82393",
    images: ["https://www.figma.com/api/mcp/asset/c4064624-f944-4dc7-ba93-2fdcc3f82393"],
    featured: true,
    status: "published",
    createdAt: now,
  },
  {
    id: "aureon",
    slug: "aureon",
    title: "Aureon",
    client: "Aureon",
    year: 2025,
    category: "Brand Identity",
    tags: ["Branding", "Hospitality"],
    description: "A hospitality identity system built around material contrast, light, and sculptural typography.",
    body: "Aureon uses atmosphere, restraint, and sculptural forms to define a hospitality-first brand world.",
    coverImage: "https://www.figma.com/api/mcp/asset/132e5a3c-6b20-436e-aa56-ef5dd07a3602",
    images: ["https://www.figma.com/api/mcp/asset/132e5a3c-6b20-436e-aa56-ef5dd07a3602"],
    featured: true,
    status: "published",
    createdAt: now,
  },
  {
    id: "lume-agency",
    slug: "lume-agency",
    title: "Lume Agency",
    client: "Lume Agency",
    year: 2025,
    category: "Art Direction",
    tags: ["Art Direction", "Campaign"],
    description: "Editorial systems and campaign imagery shaped into a flexible identity for a creative agency.",
    body: "Lume Agency blends editorial photography and campaign systems into a flexible identity toolkit.",
    coverImage: "https://www.figma.com/api/mcp/asset/9650bd78-2dde-4c08-aba1-336936e6e92d",
    images: ["https://www.figma.com/api/mcp/asset/9650bd78-2dde-4c08-aba1-336936e6e92d"],
    featured: true,
    status: "published",
    createdAt: now,
  },
  {
    id: "avenir-motors",
    slug: "avenir-motors",
    title: "Avenir Motors",
    client: "Avenir Motors",
    year: 2025,
    category: "Visual Identity",
    tags: ["Art Direction", "Automotive"],
    description: "A performance-first visual language for a future-facing automotive concept.",
    body: "Avenir Motors uses speed, shadow, and contrast to present a future-facing performance concept.",
    coverImage: "https://www.figma.com/api/mcp/asset/e51e05f9-d12b-482e-96a9-7174b81ebaf2",
    images: ["https://www.figma.com/api/mcp/asset/e51e05f9-d12b-482e-96a9-7174b81ebaf2"],
    featured: true,
    status: "published",
    createdAt: now,
  },
  {
    id: "nova-frame",
    slug: "nova-frame",
    title: "Nova Frame",
    client: "Nova Frame",
    year: 2025,
    category: "Product Identity",
    tags: ["Website", "Product"],
    description: "A crisp launch identity and digital system for a product company working at the edge of industrial design.",
    body: "Nova Frame frames hardware tactility and minimal interface language inside a launch-ready digital system.",
    coverImage: "https://www.figma.com/api/mcp/asset/ace928fa-6dbd-47f4-a560-3cec8d865d4d",
    images: ["https://www.figma.com/api/mcp/asset/ace928fa-6dbd-47f4-a560-3cec8d865d4d"],
    featured: false,
    status: "published",
    createdAt: now,
  },
  {
    id: "obsidian",
    slug: "obsidian",
    title: "Obsidian",
    client: "Obsidian",
    year: 2025,
    category: "Brand Identity",
    tags: ["Packaging", "Branding"],
    description: "Brand architecture and tactile product storytelling for a high-contrast consumer launch.",
    body: "Obsidian is a tactile, high-contrast brand system made for a product launch with strong material cues.",
    coverImage: "https://www.figma.com/api/mcp/asset/506e7181-6c3b-46a8-ada5-dcf44d838cba",
    images: ["https://www.figma.com/api/mcp/asset/506e7181-6c3b-46a8-ada5-dcf44d838cba"],
    featured: false,
    status: "published",
    createdAt: now,
  },
  {
    id: "terran-collective",
    slug: "terran-collective",
    title: "Terran Collective",
    client: "Terran Collective",
    year: 2024,
    category: "Visual Identity",
    tags: ["Branding", "Landscape"],
    description: "An earthy, atmospheric identity built for a collective working between architecture and landscape.",
    body: "Terran Collective balances earthy textures and calm structure across an architectural identity system.",
    coverImage: "https://www.figma.com/api/mcp/asset/b92fbbed-b2aa-4187-bc3c-acbc7651407d",
    images: ["https://www.figma.com/api/mcp/asset/b92fbbed-b2aa-4187-bc3c-acbc7651407d"],
    featured: false,
    status: "published",
    createdAt: now,
  },
  {
    id: "halo-visual",
    slug: "halo-visual",
    title: "Halo Visual",
    client: "Halo Visual",
    year: 2024,
    category: "Motion Design",
    tags: ["Motion", "Editorial"],
    description: "A motion-led visual system with a cinematic rhythm and image-first storytelling.",
    body: "Halo Visual treats motion as the organizing principle for a cinematic, image-first brand system.",
    coverImage: "https://www.figma.com/api/mcp/asset/edd44ca3-20b3-4dbf-8e6f-4fd1e2b0eb44",
    images: ["https://www.figma.com/api/mcp/asset/edd44ca3-20b3-4dbf-8e6f-4fd1e2b0eb44"],
    featured: false,
    status: "published",
    createdAt: now,
  },
  {
    id: "flux-division",
    slug: "flux-division",
    title: "Flux Division",
    client: "Flux Division",
    year: 2024,
    category: "Digital Experience",
    tags: ["Website", "Motion"],
    description: "A digital identity built from motion, depth, and precise image sequencing.",
    body: "Flux Division is a digital identity shaped by motion, sequencing, and controlled visual depth.",
    coverImage: "https://www.figma.com/api/mcp/asset/9dd4e558-aaba-42cc-afd6-e49140a81477",
    images: ["https://www.figma.com/api/mcp/asset/9dd4e558-aaba-42cc-afd6-e49140a81477"],
    featured: false,
    status: "published",
    createdAt: now,
  },
  {
    id: "neutra-lab",
    slug: "neutra-lab",
    title: "Neutra Lab",
    client: "Neutra Lab",
    year: 2024,
    category: "Visual Identity",
    tags: ["Website", "Product"],
    description: "A product and motion system shaped around hardware tactility and minimal interfaces.",
    body: "Neutra Lab combines hardware tactility and minimal interface thinking inside a polished brand world.",
    coverImage: "https://www.figma.com/api/mcp/asset/438948ec-f3a3-489f-b438-4d602d883e94",
    images: ["https://www.figma.com/api/mcp/asset/438948ec-f3a3-489f-b438-4d602d883e94"],
    featured: false,
    status: "published",
    createdAt: now,
  },
  {
    id: "solari-house",
    slug: "solari-house",
    title: "Solari House",
    client: "Solari House",
    year: 2024,
    category: "Brand Identity",
    tags: ["Branding", "Interiors"],
    description: "A warm, elevated identity for an interiors brand rooted in material depth and restraint.",
    body: "Solari House is a warm interiors identity built on restraint, light, and tactile material contrast.",
    coverImage: "https://www.figma.com/api/mcp/asset/794a2004-a5b7-4bb5-8b88-c7c2d95003b1",
    images: ["https://www.figma.com/api/mcp/asset/794a2004-a5b7-4bb5-8b88-c7c2d95003b1"],
    featured: false,
    status: "published",
    createdAt: now,
  },
];
